load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")

genrule(
    name = "factorio-world",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["factorio-world_0.18.2.zip"],
    cmd_bash = "./mods/download.sh $@ 4699eed61dc2f49dab9c1020a7066ba50328fbc0 $<",
)

genrule(
    name = "Enhanced_Map_Colors",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["Enhanced_Map_Colors_1.5.3.zip"],
    cmd_bash = "./mods/download.sh $@ 02552e2caf562fe27fb7b7a16fa6ee6976b23d8b $<",
)

genrule(
    name = "DiscoScience",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["DiscoScience_1.0.2.zip"],
    cmd_bash = "./mods/download.sh $@ 4f1fd314636422fb8e5ff5a8a4848f00b223aeac $<",
)

genrule(
    name = "BigDrills",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["BigDrills_0.5.9.zip"],
    cmd_bash = "./mods/download.sh $@ 36315d85349d8ab7b213b804b17faae85e6b3d06 $<",
)

genrule(
    name = "textplates",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["textplates_0.5.3.zip"],
    cmd_bash = "./mods/download.sh $@ b598366afb8b2e4129c732af98b32f4b6ea99b41 $<",
)

genrule(
    name = "Waterfill",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["Waterfill_v17_0.18.0.zip"],
    cmd_bash = "./mods/download.sh $@ 90eabdf3e5895195bca9fe7332ce35789281d35b $<",
)

genrule(
    name = "beautiful_bridge_railway",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["beautiful_bridge_railway_0.18.1.zip"],
    cmd_bash = "./mods/download.sh $@ 6865873330e52f44bb8f4c3ffa6d1ec220161d05 $<",
)

genrule(
    name = "blueprint_flip_and_turn",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["blueprint_flip_and_turn_18.7.0.zip"],
    cmd_bash = "./mods/download.sh $@ e2966181fb9b19b79630b3a62cc3702154e8fbb5 $<",
)

genrule(
    name = "ElectricTrain",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["ElectricTrain_0.18.1.zip"],
    cmd_bash = "./mods/download.sh $@ 0acb16e8416877177388ee63063d984fd7e29de6 $<",
)

genrule(
    name = "Todo-List",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["Todo-List_18.0.1.zip"],
    cmd_bash = "./mods/download.sh $@ 0ed1586e6f58588267b88d5089c52f9ee7eb68b1 $<",
)

genrule(
    name = "MaxRateCalculator",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["MaxRateCalculator_3.4.46.zip"],
    cmd_bash = "./mods/download.sh $@ ad3a3a79145e5b9f4d12efc303f2f378befcc3e9 $<",
)

genrule(
    name = "Bottleneck",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["Bottleneck_0.11.4.zip"],
    cmd_bash = "./mods/download.sh $@ 3b194f6ff8a1853d3906716dfb13d27090747690 $<",
)

genrule(
    name = "nixie-tubes",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["nixie-tubes_0.18.5.zip"],
    cmd_bash = "./mods/download.sh $@ 5233232aa1d355d1a4cf99ad4e1095ede5f2a77c $<",
)

genrule(
    name = "Big_Brother",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["Big_Brother_0.5.3.zip"],
    cmd_bash = "./mods/download.sh $@ a9eacec3433380fd5b1d70d273131956794d8597 $<",
)

genrule(
    name = "Warehousing",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["Warehousing_0.3.1.zip"],
    cmd_bash = "./mods/download.sh $@ 6884869fd01aad7e9deef5646b3b4ace3527cce9 $<",
)

genrule(
    name = "Aircraft",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["Aircraft_1.7.1.zip"],
    cmd_bash = "./mods/download.sh $@ 3a46890b6ae4d1d3693af9cde1e75e612e312f3c $<",
)

genrule(
    name = "cargo-ships",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["cargo-ships_0.0.55.zip"],
    cmd_bash = "./mods/download.sh $@ d65c9481a801a5f703f7ac2e535bc87d64323574 $<",
)

genrule(
    name = "WaterWell",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["WaterWell_1.0.21.zip"],
    cmd_bash = "./mods/download.sh $@ 83e15a4e66aad0ab6bd75f3c5c35d137d79d151e $<",
)

genrule(
    name = "bobequipment",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobequipment_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ b471da0b28bc96a33fa81495aef1d6fe3d107017 $<",
)

genrule(
    name = "bobclasses",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobclasses_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ c6e665fc8e23a0a647d4af5db35e036ece250d04 $<",
)

genrule(
    name = "clock",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["clock_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ f18956c24bcc6f86f85f10ac665a9b00f7671ee9 $<",
)

genrule(
    name = "bobgreenhouse",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobgreenhouse_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ 00f3b1bd242d08ee8204fa2ce3295922c49e7761 $<",
)

genrule(
    name = "bobvehicleequipment",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobvehicleequipment_1.0.1.zip"],
    cmd_bash = "./mods/download.sh $@ 534a411bdf396050701d3934d018fc16741cfac6 $<",
)

genrule(
    name = "bobenemies",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobenemies_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ 913c415e560f3c36e9a67e72b3e3bc9748b2c425 $<",
)

genrule(
    name = "bobores",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobores_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ 9d077213259f9f8558d284aa9c7cbc459b0166c4 $<",
)

genrule(
    name = "bobmodules",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobmodules_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ 4db5bd467c968e9f1eb3b9b29c3683da5dcaa0f4 $<",
)

genrule(
    name = "bobelectronics",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobelectronics_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ eb63d5887343fcec93f053cc86426c1305e73e30 $<",
)

genrule(
    name = "bobrevamp",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobrevamp_1.0.1.zip"],
    cmd_bash = "./mods/download.sh $@ 869173f98e156205785720c98606556f51ea89df $<",
)

genrule(
    name = "bobtech",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobtech_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ 1fd83746706141cc0e2d883f57fdb535a54b0621 $<",
)

genrule(
    name = "bobmining",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobmining_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ 3547704f7ab80d14fb0ad25a5f6293f418c16890 $<",
)

genrule(
    name = "bobassembly",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobassembly_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ 0c77d32d56331ddc1ba16e0d2ebc39a94b4fda43 $<",
)

genrule(
    name = "bobwarfare",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobwarfare_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ 63ba3d1cd33df54686d8cccb405d012d92a51d50 $<",
)

genrule(
    name = "bobinserters",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobinserters_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ b641dcb3828e519c321f063552e07e6c28a942ec $<",
)

genrule(
    name = "bobpower",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobpower_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ 333e7aed5f21a4b5c7dac172489fa7e9b7b932e9 $<",
)

genrule(
    name = "bobplates",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["bobplates_1.0.2.zip"],
    cmd_bash = "./mods/download.sh $@ aa86ec57c6d20f62c4969c5ad1b9b1aa3204a836 $<",
)

genrule(
    name = "boblogistics",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["boblogistics_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ fd7d2c847747e5eb0e6a597852a0578a6c0ca520 $<",
)

genrule(
    name = "boblibrary",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["boblibrary_1.0.0.zip"],
    cmd_bash = "./mods/download.sh $@ e5c444aaeca221389ec9bf6cf83c0d6017ed4e22 $<",
)

genrule(
    name = "FARL",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["FARL_4.0.5.zip"],
    cmd_bash = "./mods/download.sh $@ a404a095fc9a4456e3bb8c21d61a8c84bea702c7 $<",
)

genrule(
    name = "Armored-train",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["Armored-train_0.3.12.zip"],
    cmd_bash = "./mods/download.sh $@ 6cf47c85a28269d7bc888cc3b0771e9d6471cb0e $<",
)

genrule(
    name = "train-pubsub",
    tools = ["download.sh"],
    srcs = ["authentication.json"],
    outs = ["train-pubsub_1.0.5.zip"],
    cmd_bash = "./mods/download.sh $@ ea3aa80873c5d194239f23822039d97521a5346a $<",
)

pkg_tar(
    name = "pkg",
    srcs = [
        ":factorio-world",
        ":Enhanced_Map_Colors",
        ":DiscoScience",
        ":BigDrills",
        ":textplates",
        ":Waterfill",
        ":beautiful_bridge_railway",
        ":blueprint_flip_and_turn",
        ":ElectricTrain",
        ":Todo-List",
        ":MaxRateCalculator",
        ":Bottleneck",
        ":nixie-tubes",
        ":Big_Brother",
        ":Warehousing",
        ":Aircraft",
        ":cargo-ships",
        ":WaterWell",
        ":bobequipment",
        ":bobclasses",
        ":clock",
        ":bobgreenhouse",
        ":bobvehicleequipment",
        ":bobenemies",
        ":bobores",
        ":bobmodules",
        ":bobelectronics",
        ":bobrevamp",
        ":bobtech",
        ":bobmining",
        ":bobassembly",
        ":bobwarfare",
        ":bobinserters",
        ":bobpower",
        ":bobplates",
        ":boblogistics",
        ":boblibrary",
        ":FARL",
        ":Armored-train",
        ":train-pubsub",
    ],
    package_dir = "/opt/local/factorio/mods",
    visibility = ["//visibility:public"],
)
